spring:
  datasource:
    url: jdbc:mysql://likeminded-database-1.crmcuycuw4jy.ap-southeast-1.rds.amazonaws.com:3306/like_minded?useSSL=true
    username: admin
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-lifetime: 6000
    hikari:
      keep-alive-time:240000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: +08:00

  server:
    servlet:
      context-path:

  devtools:
    restart:
      exclude: static/**,public/**
      additional-paths: src/main/java
logging:
  level:
    root: info
    org:
      springframework: info
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 3