spring:
  datasource:
    url: jdbc:mysql://likeminded-database-1.crmcuycuw4jy.ap-southeast-1.rds.amazonaws.com:3306/like_minded?useSSL=true
    username: admin
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-lifetime: 6000
    hikari:
      keep-alive-time:240000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: +08:00

  server:
    servlet:
      context-path:

  devtools:
    restart:
      exclude: static/**,public/**
      additional-paths: src/main/java
logging:
  file:
    name: server.log

  level:
    root: info
    org.springframework: info
    org.hibernate: info
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3