name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/spring-boot-cicd:latest
      - name: Delete Old Docker container
        run: sudo docker rm -f spring-boot-cicd-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name spring-boot-cicd-container ${{ secrets.DOCKER_USERNAME }}/spring-boot-cicd:latest