name: Production CD Pipeline

on: workflow_dispatch

jobs:
  deploy:
    runs-on: [self-hosted, oracle-vps]

    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/like-minded-api-prod:latest
      - name: Delete Old Docker container
        run: sudo docker rm -f like-minded-api-prod-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8081:8080 --name like-minded-api-prod-container ${{ secrets.DOCKER_USERNAME }}/like-minded-api-prod:latest